name: realtime-messenger

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    image: 'rabbitmq:4-management'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:15691:15691"
      - "127.0.0.1:15692:15692"
      - "127.0.0.1:25672:25672"
      - "127.0.0.1:4369:4369"
      - "127.0.0.1:45781:45781"
      - "127.0.0.1:5671:5671"
      - "127.0.0.1:61613:61613"
    volumes:
      - ./data/rabbitmq_data:/data
    env_file:
      - .env


  online-tracking-service:
    container_name: ${COMPOSE_PROJECT_NAME}-ots
    image: 'online-tracking-service'
    ports:
      - "127.0.0.1:50051:50051"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  realtime-messenger:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    image: 'realtime-messenger'
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      online-tracking-service:
        condition: service_started
#volumes:
#  postgres_data:
#  rabbitmq_data: