name: realtime-messenger

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
    ports:
      - '5672'
    volumes:
      - ./data/rabbitmq_data:/data
    env_file:
      - .env
#
#
#volumes:
#  postgres_data:
#  rabbitmq_data: